"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ".//globals.css";
import { Navbar } from "./component/Navbar";
import { Footer } from "./component/footer";
import "flowbite";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <Navbar />

        <div>
          {/* <img
            src="/images/bg_image.png"
            alt="bg_image"
            className="absolute left-0 right-0 m-auto z-11 opacity-15 p-24 "
          /> */}
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}



